/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import MySQL.AvionSQL;
import MySQL.ConexionSQL;
import Negocio.Hora;


public class MenuVuelos extends javax.swing.JFrame {

    /**
     * Creates new form MenuVuelos
     */
    
    AvionSQL avion;
    Hora hora;

    public MenuVuelos() {
        initComponents();
        hora = new Hora();
        avion = new AvionSQL();
        mostrarTabla();
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setImageLabel(jLabel14, "src/Interfaz/peligro_senal.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTFOrigen1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFDestino1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFAvion1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFCompania1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFHoraSalida1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFHoraLlegada1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jBAgregar1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFAvion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCompania = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFHoraSalida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFHoraLlegada = new javax.swing.JTextField();
        jCBCompania = new javax.swing.JCheckBox();
        jCBOrigen = new javax.swing.JCheckBox();
        jCBHoraSalida = new javax.swing.JCheckBox();
        jCBDestino = new javax.swing.JCheckBox();
        jCBHoraLlegada = new javax.swing.JCheckBox();
        jCBAvionid = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBAgregar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTFAvionid = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jBAborrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTFAvionid1 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMIAsientos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMIRegresar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane1AncestorAdded(evt);
            }

            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }

            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel7.setText("Origen:");

        jTFOrigen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFOrigen1ActionPerformed(evt);
            }
        });
        jTFOrigen1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFOrigen1KeyPressed(evt);
            }
        });

        jLabel8.setText("Destino:");

        jTFDestino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDestino1ActionPerformed(evt);
            }
        });
        jTFDestino1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDestino1KeyPressed(evt);
            }
        });

        jLabel9.setText("Avion ID:");

        jTFAvion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAvion1ActionPerformed(evt);
            }
        });
        jTFAvion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAvion1KeyPressed(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAvion1KeyTyped(evt);
            }
        });

        jLabel10.setText("Compañia:");

        jLabel11.setText("Hora de Salida:");

        jLabel12.setText("Hora de Llegada:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jLabel10,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 63,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel9,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jTFOrigen1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                199, Short.MAX_VALUE)
                                                        .addComponent(jTFCompania1)
                                                        .addComponent(jTFAvion1)))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jTFDestino1)
                                                        .addComponent(jTFHoraLlegada1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 199,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jTFHoraSalida1))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jTFAvion1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTFCompania1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTFOrigen1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jTFHoraSalida1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTFDestino1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jTFHoraLlegada1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Vuelos"));

        mostrarTabla();
        // jTable2.setModel(new javax.swing.table.DefaultTableModel(
        // new Object [][] {
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null}
        // },
        // new String [] {
        // "Avion_id", "Compañia", "Origen", "Hora Salida", "Destino", "Hora Llegada"
        // }
        // ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2)
                                .addContainerGap()));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBAgregar1.setText("Agregar");
        jBAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jBAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(121, Short.MAX_VALUE)));
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBAgregar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Ingreso Datos", jPanel4);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("Origen:");

        jTFOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFOrigenActionPerformed(evt);
            }
        });
        jTFOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFOrigenKeyPressed(evt);
            }
        });

        jLabel2.setText("Destino:");

        jTFDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDestinoActionPerformed(evt);
            }
        });
        jTFDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDestinoKeyPressed(evt);
            }
        });

        jLabel3.setText("Avion ID:");

        jTFAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAvionActionPerformed(evt);
            }
        });
        jTFAvion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAvionKeyPressed(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAvionKeyTyped(evt);
            }
        });

        jLabel4.setText("Compañia:");

        jLabel5.setText("Hora de Salida:");

        jLabel6.setText("Hora de Llegada:");

        jCBAvionid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAvionidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jTFDestino, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                163, Short.MAX_VALUE)
                                                        .addComponent(jTFHoraSalida)
                                                        .addComponent(jTFHoraLlegada))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jCBDestino,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBHoraSalida,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBHoraLlegada,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jLabel4,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 63,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel3,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jTFOrigen, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                163, Short.MAX_VALUE)
                                                        .addComponent(jTFCompania)
                                                        .addComponent(jTFAvion))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jCBOrigen, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBCompania, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCBAvionid, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addGap(16, 16, 16)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(jTFAvion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCBAvionid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBCompania)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4)
                                                .addComponent(jTFCompania, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(jTFOrigen, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCBOrigen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel5)
                                                .addComponent(jTFHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCBHoraSalida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(jTFDestino, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCBDestino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel6)
                                                .addComponent(jTFHoraLlegada, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jCBHoraLlegada))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Vuelos"));

        // jTable1.setModel(new javax.swing.table.DefaultTableModel(
        // new Object [][] {
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null},
        // {null, null, null, null, null, null}
        // },
        // new String [] {
        // "Avion_id", "Compañia", "Origen", "Hora Salida", "Destino", "Hora Llegada"
        // }
        // ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addContainerGap()));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jLabel13.setText("Avion ID:");

        jTFAvionid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAvionidActionPerformed(evt);
            }
        });
        jTFAvionid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAvionidKeyPressed(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAvionidKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFAvionid, javax.swing.GroupLayout.PREFERRED_SIZE, 151,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addComponent(jTFAvionid, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Actualizar", jPanel5);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBAborrar.setText("Borrar");
        jBAborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAborrarActionPerformed(evt);
            }
        });

        jLabel20.setText("Avion ID:");

        jTFAvionid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAvionid1ActionPerformed(evt);
            }
        });
        jTFAvionid1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFAvionid1KeyPressed(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFAvionid1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFAvionid1, javax.swing.GroupLayout.PREFERRED_SIZE, 151,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        jPanel11Layout.setVerticalGroup(
                jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBAborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel20)
                                        .addComponent(jTFAvionid1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla de Vuelos"));

        // jTable3.setModel(new javax.swing.table.DefaultTableModel(
        //         new Object[][] {
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null },
        //                 { null, null, null, null, null, null }
        //         },
        //         new String[] {
        //                 "Avion_id", "Compañia", "Origen", "Hora Salida", "Destino", "Hora Llegada"
        //         }));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addContainerGap()));

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 251,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel9Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(42, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Borrar", jPanel9);

        jMenu1.setText("File");

        jMIAsientos.setText("Asientos");
        jMIAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAsientosActionPerformed(evt);
            }
        });
        jMenu1.add(jMIAsientos);
        jMenu1.add(jSeparator1);

        jMIRegresar.setText("Regresar");
        jMIRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegresarActionPerformed(evt);
            }
        });
        jMenu1.add(jMIRegresar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(11, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAsientosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMIAsientosActionPerformed
        JFAsientos asiento = new JFAsientos();
        asiento.setVisible(true);
        setVisible(false);
    }// GEN-LAST:event_jMIAsientosActionPerformed

    //agregar imagen
    public void setImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // mostrar datos
    public void mostrarTabla() {
        Connection con;
        Statement stmt;
        ConexionSQL conectar = new ConexionSQL();
        con = conectar.getconetion();

        String sql = "SELECT * FROM avion";

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Avion_ID");
        model.addColumn("Compañia");
        model.addColumn("Origen");
        model.addColumn("Hora de salida");
        model.addColumn("Destino");
        model.addColumn("Hola de llegada");

        jTable1.setModel(model);
        jTable2.setModel(model);
        jTable3.setModel(model);

        String[] datos = new String[6];
        try {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                model.addRow(datos);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void jTFOrigen1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFOrigen1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFOrigen1ActionPerformed

    private void jTFOrigen1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFOrigen1KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFOrigen1KeyPressed

    private void jTFDestino1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFDestino1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFDestino1ActionPerformed

    private void jTFDestino1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFDestino1KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFDestino1KeyPressed

    private void jTFAvion1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFAvion1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvion1ActionPerformed

    private void jTFAvion1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvion1KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvion1KeyPressed

    private void jTFAvion1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvion1KeyTyped
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvion1KeyTyped
    /*
     * boton1
     */

    private void jBAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAgregar1ActionPerformed
        try {
            int avionid = Integer.parseInt(this.jTFAvion1.getText());
            String compania = this.jTFCompania1.getText();
            String origen = this.jTFOrigen1.getText();
            String hora_Salida = this.jTFHoraSalida1.getText();
            String destino = this.jTFDestino1.getText();
            String hora_Llegada = this.jTFHoraLlegada1.getText();

            if (hora.verificarHora(hora_Llegada) && hora.verificarHora(hora_Salida)) {
                if (avionid > 0) {
                    avion.insertarAvion(avionid, compania, origen, hora_Salida, destino, hora_Llegada);

                    mostrarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo, debe ser un numero positivo");
                }

            } else {
                JOptionPane.showMessageDialog(null, "formato de la hora (h:m:s)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo, debe ser un numero");
        }

    }// GEN-LAST:event_jBAgregar1ActionPerformed

    private void jTFOrigenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFOrigenActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFOrigenActionPerformed

    private void jTFOrigenKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFOrigenKeyPressed
        // char variable = evt.getKeyChar();
        // if(Character.isDigit(variable)){
        // Toolkit.getDefaultToolkit().beep();
        // evt.consume();
        // JOptionPane.showMessageDialog(null, "Debe ingresar la ciudad de Origen",
        // "Información",
        // JOptionPane.WARNING_MESSAGE);
        // }
    }// GEN-LAST:event_jTFOrigenKeyPressed

    private void jTFDestinoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFDestinoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFDestinoActionPerformed

    private void jTFDestinoKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFDestinoKeyPressed
        // char variable = evt.getKeyChar();
        // if(Character.isDigit(variable)){
        // Toolkit.getDefaultToolkit().beep();
        // evt.consume();
        // JOptionPane.showMessageDialog(null, "Debe ingresar la ciudad de Destino",
        // "Información",
        // JOptionPane.WARNING_MESSAGE);
        // }

    }// GEN-LAST:event_jTFDestinoKeyPressed

    private void jTFAvionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFAvionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionActionPerformed
    /*
     * avion id
     */

    private void jTFAvionKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionKeyPressed
        // char variable = evt.getKeyChar();
        // if(Character.isLetter(variable)){
        // Toolkit.getDefaultToolkit().beep();
        // evt.consume();
        // JOptionPane.showMessageDialog(null, "Debe ingresar el ID del Avión",
        // "Información",
        // JOptionPane.WARNING_MESSAGE);
        // }else if
        // (evt.getKeyCode()==KeyEvent.VK_SUBTRACT||evt.getKeyCode()==KeyEvent.VK_MINUS){
        // Toolkit.getDefaultToolkit().beep();
        // evt.consume();
        // JOptionPane.showMessageDialog(null, "Ingrese correctamente el ID");
        // this.jTFAvion.setText("");
        // }
    }// GEN-LAST:event_jTFAvionKeyPressed

    private void jTFAvionKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionKeyTyped
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionKeyTyped

    private void jCBAvionidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCBAvionidActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCBAvionidActionPerformed
    /*
     * boton2
     */

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAgregarActionPerformed
        try {
            int avion_id = Integer.parseInt(this.jTFAvionid.getText());
            if (avion_id > 0) {
                if (this.jCBAvionid.isSelected()) {
                    int update = Integer.parseInt(this.jTFAvion.getText());
                    if (update > 0) {
                        avion.UpdateAvion(avion_id, 1, "" + update);
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "Formato ID ingresado erroneo, debe ser un numero positivo");
                    }
                }
                if (this.jCBCompania.isSelected()) {
                    String update = this.jTFCompania.getText();
                    avion.UpdateAvion(avion_id, 2, update);
                }
                if (this.jCBOrigen.isSelected()) {
                    String update = this.jTFOrigen.getText();
                    avion.UpdateAvion(avion_id, 3, update);
                }
                if (this.jCBHoraLlegada.isSelected()) {
                    String update = this.jTFHoraLlegada.getText();
                    if (hora.verificarHora(update)) {
                        avion.UpdateAvion(avion_id, 4, update);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se actualizo la hora\nFormato de la hora (h:m:s)");
                    }
                }
                if (this.jCBDestino.isSelected()) {
                    String update = this.jTFDestino.getText();
                    avion.UpdateAvion(avion_id, 5, update);
                }
                if (this.jCBHoraSalida.isSelected()) {
                    String update = this.jTFHoraSalida.getText();
                    if (hora.verificarHora(update)) {
                        avion.UpdateAvion(avion_id, 6, update);
                    } else {
                        JOptionPane.showMessageDialog(null, "No se actualizo la hora\nFormato de la hora (h:m:s)");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo, debe ser un numero positivo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo");
        }

        mostrarTabla();
    }// GEN-LAST:event_jBAgregarActionPerformed

    private void jTFAvionidActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFAvionidActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionidActionPerformed

    private void jTFAvionidKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionidKeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionidKeyPressed

    private void jTFAvionidKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionidKeyTyped
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionidKeyTyped
    /*
     * boton3
     */

    private void jBAborrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBAgregar2ActionPerformed
        try {
            int avionid = Integer.parseInt(this.jTFAvionid1.getText());
            if (avionid > 0) {
                int option = JOptionPane.showConfirmDialog(null, "estas seguro de eliminar este dato de la lista?","Borrar",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
                if (option==0) {
                    avion.borrarAvion(avionid);
                    JOptionPane.showMessageDialog(null, "Dato eliminado");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo, debe ser un numero positivo");
            }
            mostrarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato ID ingresado erroneo, debe ser un numero");
        }

    }// GEN-LAST:event_jBAgregar2ActionPerformed

    private void jTFAvionid1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTFAvionid1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionid1ActionPerformed

    private void jTFAvionid1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionid1KeyPressed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionid1KeyPressed

    private void jTFAvionid1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFAvionid1KeyTyped
        // TODO add your handling code here:
    }// GEN-LAST:event_jTFAvionid1KeyTyped

    private void jTabbedPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {// GEN-FIRST:event_jTabbedPane1AncestorAdded
        // TODO add your handling code here:
    }// GEN-LAST:event_jTabbedPane1AncestorAdded

    private void jMIRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        JFEscritorio desktop = new JFEscritorio();
        desktop.setVisible(true);
        setVisible(false);
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAborrar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBAgregar1;
    private javax.swing.JCheckBox jCBAvionid;
    private javax.swing.JCheckBox jCBCompania;
    private javax.swing.JCheckBox jCBDestino;
    private javax.swing.JCheckBox jCBHoraLlegada;
    private javax.swing.JCheckBox jCBHoraSalida;
    private javax.swing.JCheckBox jCBOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMIAsientos;
    private javax.swing.JMenuItem jMIRegresar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTFAvion;
    private javax.swing.JTextField jTFAvion1;
    private javax.swing.JTextField jTFAvionid;
    private javax.swing.JTextField jTFAvionid1;
    private javax.swing.JTextField jTFCompania;
    private javax.swing.JTextField jTFCompania1;
    private javax.swing.JTextField jTFDestino;
    private javax.swing.JTextField jTFDestino1;
    private javax.swing.JTextField jTFHoraLlegada;
    private javax.swing.JTextField jTFHoraLlegada1;
    private javax.swing.JTextField jTFHoraSalida;
    private javax.swing.JTextField jTFHoraSalida1;
    private javax.swing.JTextField jTFOrigen;
    private javax.swing.JTextField jTFOrigen1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
